### ISSUE TITLE
starred articles not addressable anymore since update

### ISSUE THREAD

**Issue by joolz** [mardy/ttrss#9]
Maybe it's me, but since the last update 0.5.2-2 I cannot get to the starred articles anymore. Use case:
- read all articles (so there are no more unread articles)
- restart the app
- nothing in the Unread tab (as expected)
- go to the All tab: nothing there (I would expect my read starred articles here)

and, as an extra (small) issue: when I now go back (press "<"), I end up with a white screen, no more navigation is possible.

**Comment by mardy** [comment]
The back arrow leading to a white screen is a bug in the UI toolkit, they'll fix with soon:
https://bugs.launchpad.net/ubuntu/+source/ubuntu-ui-toolkit/+bug/1565811

As for the starred articles, I will investigate it; however, I don't think that it's a regression, as since the last version I only made visual changes, and the data models where not touched. So I suspect that if this doesn't work, it actually didn't work even before.
